#-------------------------------------------------
#
# Project created by QtCreator 2017-08-16T16:04:07
#
#-------------------------------------------------

QT       += core gui widgets serialport network qml sql location

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = earthstation
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


SOURCES += \
    mainwindow.cpp \
    config.cpp \
    main.cpp \
    telemetry.cpp \
    lib/qInstrument/qinstrument.cpp \
    lib/ExtPlane-Panel-master/dialogs/bindingcurvedialog.cpp \
    lib/ExtPlane-Panel-master/dialogs/edititemdialog.cpp \
    lib/ExtPlane-Panel-master/dialogs/hardwaredialog.cpp \
    lib/ExtPlane-Panel-master/dialogs/panelitemselectiondialog.cpp \
    lib/ExtPlane-Panel-master/dialogs/panelsdialog.cpp \
    lib/ExtPlane-Panel-master/dialogs/settingsdialog.cpp \
    lib/ExtPlane-Panel-master/hardware/chromaoutputdevice.cpp \
    lib/ExtPlane-Panel-master/hardware/hardwarebinding.cpp \
    lib/ExtPlane-Panel-master/hardware/hardwaremanager.cpp \
    lib/ExtPlane-Panel-master/hardware/nulloutputdevice.cpp \
    lib/ExtPlane-Panel-master/hardware/outputdevice.cpp \
    lib/ExtPlane-Panel-master/hardware/pololuoutputdevice.cpp \
    lib/ExtPlane-Panel-master/hardware/servoblasteroutputdevice.cpp \
    lib/ExtPlane-Panel-master/needles/gabalancedneedle.cpp \
    lib/ExtPlane-Panel-master/needles/needle.cpp \
    lib/ExtPlane-Panel-master/needles/triangleneedle.cpp \
    lib/ExtPlane-Panel-master/panelitems/airspeedindicator.cpp \
    lib/ExtPlane-Panel-master/panelitems/altimeter.cpp \
    lib/ExtPlane-Panel-master/panelitems/attitudeindicator.cpp \
    lib/ExtPlane-Panel-master/panelitems/button.cpp \
    lib/ExtPlane-Panel-master/panelitems/compass.cpp \
    lib/ExtPlane-Panel-master/panelitems/datarefdebugger.cpp \
    lib/ExtPlane-Panel-master/panelitems/di.cpp \
    lib/ExtPlane-Panel-master/panelitems/dial.cpp \
    lib/ExtPlane-Panel-master/panelitems/displayinstrument.cpp \
    lib/ExtPlane-Panel-master/panelitems/engine_battery.cpp \
    lib/ExtPlane-Panel-master/panelitems/engine_fuel_p.cpp \
    lib/ExtPlane-Panel-master/panelitems/engine_rpm.cpp \
    lib/ExtPlane-Panel-master/panelitems/enginedisplay.cpp \
    lib/ExtPlane-Panel-master/panelitems/gaugecover.cpp \
    lib/ExtPlane-Panel-master/panelitems/genericlittlegauge.cpp \
    lib/ExtPlane-Panel-master/panelitems/gpsmap.cpp \
    lib/ExtPlane-Panel-master/panelitems/hsi_ks55.cpp \
    lib/ExtPlane-Panel-master/panelitems/indicatordisplay.cpp \
    lib/ExtPlane-Panel-master/panelitems/indicatorlight.cpp \
    lib/ExtPlane-Panel-master/panelitems/mapinstrument.cpp \
    lib/ExtPlane-Panel-master/panelitems/navdisplay.cpp \
    lib/ExtPlane-Panel-master/panelitems/needleinstrument.cpp \
    lib/ExtPlane-Panel-master/panelitems/panelitem.cpp \
    lib/ExtPlane-Panel-master/panelitems/pfddisplay.cpp \
    lib/ExtPlane-Panel-master/panelitems/radarmap.cpp \
    lib/ExtPlane-Panel-master/panelitems/rotaryknob.cpp \
    lib/ExtPlane-Panel-master/panelitems/slipindicator.cpp \
    lib/ExtPlane-Panel-master/panelitems/switch.cpp \
    lib/ExtPlane-Panel-master/panelitems/tankleveler.cpp \
    lib/ExtPlane-Panel-master/panelitems/turnbank.cpp \
    lib/ExtPlane-Panel-master/panelitems/variometer.cpp \
    lib/ExtPlane-Panel-master/panelitems/raspextplaneconnection.cpp \
    lib/ExtPlane-Panel-master/util/interpolation.cpp \
    lib/ExtPlane-Panel-master/util/perlinnoise.cpp \
    lib/ExtPlane-Panel-master/widgets/colorselector.cpp \
    lib/ExtPlane-Panel-master/widgets/distanceunitcombobox.cpp \
    lib/ExtPlane-Panel-master/widgets/numberinputlineedit.cpp \
    lib/ExtPlane-Panel-master/widgets/velocityunitcombobox.cpp \
    lib/ExtPlane-Panel-master/menubutton.cpp \
    lib/ExtPlane-Panel-master/panel.cpp \
    lib/ExtPlane-Panel-master/panelitemfactory.cpp \
    lib/ExtPlane-Panel-master/panelwindow.cpp \
    lib/ExtPlane-Panel-master/settings.cpp \
    lib/ExtPlane-Panel-master/units.cpp \
    lib/ExtPlane-Panel-master/valueinterpolator.cpp \
    lib/ExtPlane-Panel-master/panelitems/clientdataref.cpp \
    lib/ExtPlane-Panel-master/panelitems/clientdatarefprovider.cpp \
    lib/ExtPlane-Panel-master/panelitems/extplaneclient.cpp \
    lib/ExtPlane-Panel-master/panelitems/extplaneconnection.cpp \
    lib/ExtPlane-Panel-master/panelitems/simulatedextplaneconnection.cpp \
    lib/ExtPlane-Panel-master/panelitems/simulateddatarefs/alternatingsimulateddataref.cpp \
    lib/ExtPlane-Panel-master/panelitems/simulateddatarefs/fixedsimulateddataref.cpp \
    lib/ExtPlane-Panel-master/panelitems/simulateddatarefs/simulateddataref.cpp \
    lib/sql.cpp \
    lib/QMapControl/Geometry.cpp                                \
    lib/QMapControl/GeometryLineString.cpp                      \
    lib/QMapControl/GeometryPoint.cpp                           \
    lib/QMapControl/GeometryPointShape.cpp                      \
    lib/QMapControl/GeometryPointShapeScaled.cpp                \
    lib/QMapControl/GeometryPointArrow.cpp                      \
    lib/QMapControl/GeometryPointCircle.cpp                     \
    lib/QMapControl/GeometryPointImage.cpp                      \
    lib/QMapControl/GeometryPointImageScaled.cpp                \
    lib/QMapControl/GeometryPolygon.cpp                         \
    lib/QMapControl/GeometryPolygonImage.cpp                    \
    lib/QMapControl/GeometryWidget.cpp                          \
    lib/QMapControl/GPS_Position.cpp                            \
    lib/QMapControl/ImageManager.cpp                            \
    lib/QMapControl/Layer.cpp                                   \
    lib/QMapControl/LayerGeometry.cpp                           \
    lib/QMapControl/LayerMapAdapter.cpp                         \
    lib/QMapControl/MapAdapter.cpp                              \
    lib/QMapControl/MapAdapterGoogle.cpp                        \
    lib/QMapControl/MapAdapterOSM.cpp                           \
    lib/QMapControl/MapAdapterTile.cpp                          \
    lib/QMapControl/MapAdapterWMS.cpp                           \
    lib/QMapControl/MapAdapterYahoo.cpp                         \
    lib/QMapControl/NetworkManager.cpp                          \
    lib/QMapControl/Projection.cpp                              \
    lib/QMapControl/ProjectionEquirectangular.cpp               \
    lib/QMapControl/ProjectionSphericalMercator.cpp             \
    lib/QMapControl/QMapControl.cpp                             \
    lib/QMapControl/QProgressIndicator.cpp


HEADERS += \
    mainwindow.h \
    config.h \
    telemetry.h \
    lib/mavlink/standard/mavlink.h \
    lib/mavlink/ardupilotmega/ardupilotmega.h \
    lib/mavlink/ardupilotmega/mavlink.h \
    lib/mavlink/ardupilotmega/mavlink_msg_adap_tuning.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ahrs.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ahrs2.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ahrs3.h \
    lib/mavlink/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ap_adc.h \
    lib/mavlink/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    lib/mavlink/ardupilotmega/mavlink_msg_battery2.h \
    lib/mavlink/ardupilotmega/mavlink_msg_camera_feedback.h \
    lib/mavlink/ardupilotmega/mavlink_msg_camera_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_compassmot_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_data16.h \
    lib/mavlink/ardupilotmega/mavlink_msg_data32.h \
    lib/mavlink/ardupilotmega/mavlink_msg_data64.h \
    lib/mavlink/ardupilotmega/mavlink_msg_data96.h \
    lib/mavlink/ardupilotmega/mavlink_msg_device_op_read.h \
    lib/mavlink/ardupilotmega/mavlink_msg_device_op_read_reply.h \
    lib/mavlink/ardupilotmega/mavlink_msg_device_op_write.h \
    lib/mavlink/ardupilotmega/mavlink_msg_device_op_write_reply.h \
    lib/mavlink/ardupilotmega/mavlink_msg_digicam_configure.h \
    lib/mavlink/ardupilotmega/mavlink_msg_digicam_control.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ekf_status_report.h \
    lib/mavlink/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    lib/mavlink/ardupilotmega/mavlink_msg_fence_point.h \
    lib/mavlink/ardupilotmega/mavlink_msg_fence_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gimbal_control.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gimbal_report.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_get_request.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_get_response.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_set_request.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_set_response.h \
    lib/mavlink/ardupilotmega/mavlink_msg_hwstatus.h \
    lib/mavlink/ardupilotmega/mavlink_msg_led_control.h \
    lib/mavlink/ardupilotmega/mavlink_msg_limits_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mag_cal_report.h \
    lib/mavlink/ardupilotmega/mavlink_msg_meminfo.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mount_configure.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mount_control.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mount_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_pid_tuning.h \
    lib/mavlink/ardupilotmega/mavlink_msg_radio.h \
    lib/mavlink/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    lib/mavlink/ardupilotmega/mavlink_msg_rally_point.h \
    lib/mavlink/ardupilotmega/mavlink_msg_rangefinder.h \
    lib/mavlink/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    lib/mavlink/ardupilotmega/mavlink_msg_rpm.h \
    lib/mavlink/ardupilotmega/mavlink_msg_sensor_offsets.h \
    lib/mavlink/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    lib/mavlink/ardupilotmega/mavlink_msg_simstate.h \
    lib/mavlink/ardupilotmega/mavlink_msg_vision_position_delta.h \
    lib/mavlink/ardupilotmega/mavlink_msg_wind.h \
    lib/mavlink/ardupilotmega/testsuite.h \
    lib/mavlink/ardupilotmega/version.h \
    lib/mavlink/ASLUAV/ASLUAV.h \
    lib/mavlink/ASLUAV/mavlink.h \
    lib/mavlink/ASLUAV/mavlink_msg_asl_obctrl.h \
    lib/mavlink/ASLUAV/mavlink_msg_aslctrl_data.h \
    lib/mavlink/ASLUAV/mavlink_msg_aslctrl_debug.h \
    lib/mavlink/ASLUAV/mavlink_msg_asluav_status.h \
    lib/mavlink/ASLUAV/mavlink_msg_ekf_ext.h \
    lib/mavlink/ASLUAV/mavlink_msg_fw_soaring_data.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_atmos.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_batmon.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_mppt.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_power.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_power_board.h \
    lib/mavlink/ASLUAV/mavlink_msg_sensorpod_status.h \
    lib/mavlink/ASLUAV/testsuite.h \
    lib/mavlink/ASLUAV/version.h \
    lib/mavlink/autoquad/autoquad.h \
    lib/mavlink/autoquad/mavlink.h \
    lib/mavlink/autoquad/mavlink_msg_aq_esc_telemetry.h \
    lib/mavlink/autoquad/mavlink_msg_aq_telemetry_f.h \
    lib/mavlink/autoquad/testsuite.h \
    lib/mavlink/autoquad/version.h \
    lib/mavlink/common/common.h \
    lib/mavlink/common/mavlink.h \
    lib/mavlink/common/mavlink_msg_actuator_control_target.h \
    lib/mavlink/common/mavlink_msg_adsb_vehicle.h \
    lib/mavlink/common/mavlink_msg_altitude.h \
    lib/mavlink/common/mavlink_msg_att_pos_mocap.h \
    lib/mavlink/common/mavlink_msg_attitude.h \
    lib/mavlink/common/mavlink_msg_attitude_quaternion.h \
    lib/mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
    lib/mavlink/common/mavlink_msg_attitude_target.h \
    lib/mavlink/common/mavlink_msg_auth_key.h \
    lib/mavlink/common/mavlink_msg_autopilot_version.h \
    lib/mavlink/common/mavlink_msg_battery_status.h \
    lib/mavlink/common/mavlink_msg_button_change.h \
    lib/mavlink/common/mavlink_msg_camera_capture_status.h \
    lib/mavlink/common/mavlink_msg_camera_image_captured.h \
    lib/mavlink/common/mavlink_msg_camera_information.h \
    lib/mavlink/common/mavlink_msg_camera_settings.h \
    lib/mavlink/common/mavlink_msg_camera_trigger.h \
    lib/mavlink/common/mavlink_msg_change_operator_control.h \
    lib/mavlink/common/mavlink_msg_change_operator_control_ack.h \
    lib/mavlink/common/mavlink_msg_collision.h \
    lib/mavlink/common/mavlink_msg_command_ack.h \
    lib/mavlink/common/mavlink_msg_command_int.h \
    lib/mavlink/common/mavlink_msg_command_long.h \
    lib/mavlink/common/mavlink_msg_control_system_state.h \
    lib/mavlink/common/mavlink_msg_data_stream.h \
    lib/mavlink/common/mavlink_msg_data_transmission_handshake.h \
    lib/mavlink/common/mavlink_msg_debug.h \
    lib/mavlink/common/mavlink_msg_debug_vect.h \
    lib/mavlink/common/mavlink_msg_distance_sensor.h \
    lib/mavlink/common/mavlink_msg_encapsulated_data.h \
    lib/mavlink/common/mavlink_msg_estimator_status.h \
    lib/mavlink/common/mavlink_msg_extended_sys_state.h \
    lib/mavlink/common/mavlink_msg_file_transfer_protocol.h \
    lib/mavlink/common/mavlink_msg_flight_information.h \
    lib/mavlink/common/mavlink_msg_follow_target.h \
    lib/mavlink/common/mavlink_msg_global_position_int.h \
    lib/mavlink/common/mavlink_msg_global_position_int_cov.h \
    lib/mavlink/common/mavlink_msg_global_vision_position_estimate.h \
    lib/mavlink/common/mavlink_msg_gps2_raw.h \
    lib/mavlink/common/mavlink_msg_gps2_rtk.h \
    lib/mavlink/common/mavlink_msg_gps_global_origin.h \
    lib/mavlink/common/mavlink_msg_gps_inject_data.h \
    lib/mavlink/common/mavlink_msg_gps_input.h \
    lib/mavlink/common/mavlink_msg_gps_raw_int.h \
    lib/mavlink/common/mavlink_msg_gps_rtcm_data.h \
    lib/mavlink/common/mavlink_msg_gps_rtk.h \
    lib/mavlink/common/mavlink_msg_gps_status.h \
    lib/mavlink/common/mavlink_msg_heartbeat.h \
    lib/mavlink/common/mavlink_msg_high_latency.h \
    lib/mavlink/common/mavlink_msg_highres_imu.h \
    lib/mavlink/common/mavlink_msg_hil_actuator_controls.h \
    lib/mavlink/common/mavlink_msg_hil_controls.h \
    lib/mavlink/common/mavlink_msg_hil_gps.h \
    lib/mavlink/common/mavlink_msg_hil_optical_flow.h \
    lib/mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
    lib/mavlink/common/mavlink_msg_hil_sensor.h \
    lib/mavlink/common/mavlink_msg_hil_state.h \
    lib/mavlink/common/mavlink_msg_hil_state_quaternion.h \
    lib/mavlink/common/mavlink_msg_home_position.h \
    lib/mavlink/common/mavlink_msg_landing_target.h \
    lib/mavlink/common/mavlink_msg_local_position_ned.h \
    lib/mavlink/common/mavlink_msg_local_position_ned_cov.h \
    lib/mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    lib/mavlink/common/mavlink_msg_log_data.h \
    lib/mavlink/common/mavlink_msg_log_entry.h \
    lib/mavlink/common/mavlink_msg_log_erase.h \
    lib/mavlink/common/mavlink_msg_log_request_data.h \
    lib/mavlink/common/mavlink_msg_log_request_end.h \
    lib/mavlink/common/mavlink_msg_log_request_list.h \
    lib/mavlink/common/mavlink_msg_logging_ack.h \
    lib/mavlink/common/mavlink_msg_logging_data.h \
    lib/mavlink/common/mavlink_msg_logging_data_acked.h \
    lib/mavlink/common/mavlink_msg_manual_control.h \
    lib/mavlink/common/mavlink_msg_manual_setpoint.h \
    lib/mavlink/common/mavlink_msg_memory_vect.h \
    lib/mavlink/common/mavlink_msg_message_interval.h \
    lib/mavlink/common/mavlink_msg_mission_ack.h \
    lib/mavlink/common/mavlink_msg_mission_clear_all.h \
    lib/mavlink/common/mavlink_msg_mission_count.h \
    lib/mavlink/common/mavlink_msg_mission_current.h \
    lib/mavlink/common/mavlink_msg_mission_item.h \
    lib/mavlink/common/mavlink_msg_mission_item_int.h \
    lib/mavlink/common/mavlink_msg_mission_item_reached.h \
    lib/mavlink/common/mavlink_msg_mission_request.h \
    lib/mavlink/common/mavlink_msg_mission_request_int.h \
    lib/mavlink/common/mavlink_msg_mission_request_list.h \
    lib/mavlink/common/mavlink_msg_mission_request_partial_list.h \
    lib/mavlink/common/mavlink_msg_mission_set_current.h \
    lib/mavlink/common/mavlink_msg_mission_write_partial_list.h \
    lib/mavlink/common/mavlink_msg_mount_orientation.h \
    lib/mavlink/common/mavlink_msg_named_value_float.h \
    lib/mavlink/common/mavlink_msg_named_value_int.h \
    lib/mavlink/common/mavlink_msg_nav_controller_output.h \
    lib/mavlink/common/mavlink_msg_optical_flow.h \
    lib/mavlink/common/mavlink_msg_optical_flow_rad.h \
    lib/mavlink/common/mavlink_msg_param_map_rc.h \
    lib/mavlink/common/mavlink_msg_param_request_list.h \
    lib/mavlink/common/mavlink_msg_param_request_read.h \
    lib/mavlink/common/mavlink_msg_param_set.h \
    lib/mavlink/common/mavlink_msg_param_value.h \
    lib/mavlink/common/mavlink_msg_ping.h \
    lib/mavlink/common/mavlink_msg_play_tune.h \
    lib/mavlink/common/mavlink_msg_position_target_global_int.h \
    lib/mavlink/common/mavlink_msg_position_target_local_ned.h \
    lib/mavlink/common/mavlink_msg_power_status.h \
    lib/mavlink/common/mavlink_msg_protocol_version.h \
    lib/mavlink/common/mavlink_msg_radio_status.h \
    lib/mavlink/common/mavlink_msg_raw_imu.h \
    lib/mavlink/common/mavlink_msg_raw_pressure.h \
    lib/mavlink/common/mavlink_msg_rc_channels.h \
    lib/mavlink/common/mavlink_msg_rc_channels_override.h \
    lib/mavlink/common/mavlink_msg_rc_channels_raw.h \
    lib/mavlink/common/mavlink_msg_rc_channels_scaled.h \
    lib/mavlink/common/mavlink_msg_request_data_stream.h \
    lib/mavlink/common/mavlink_msg_resource_request.h \
    lib/mavlink/common/mavlink_msg_safety_allowed_area.h \
    lib/mavlink/common/mavlink_msg_safety_set_allowed_area.h \
    lib/mavlink/common/mavlink_msg_scaled_imu.h \
    lib/mavlink/common/mavlink_msg_scaled_imu2.h \
    lib/mavlink/common/mavlink_msg_scaled_imu3.h \
    lib/mavlink/common/mavlink_msg_scaled_pressure.h \
    lib/mavlink/common/mavlink_msg_scaled_pressure2.h \
    lib/mavlink/common/mavlink_msg_scaled_pressure3.h \
    lib/mavlink/common/mavlink_msg_serial_control.h \
    lib/mavlink/common/mavlink_msg_servo_output_raw.h \
    lib/mavlink/common/mavlink_msg_set_actuator_control_target.h \
    lib/mavlink/common/mavlink_msg_set_attitude_target.h \
    lib/mavlink/common/mavlink_msg_set_gps_global_origin.h \
    lib/mavlink/common/mavlink_msg_set_home_position.h \
    lib/mavlink/common/mavlink_msg_set_mode.h \
    lib/mavlink/common/mavlink_msg_set_position_target_global_int.h \
    lib/mavlink/common/mavlink_msg_set_position_target_local_ned.h \
    lib/mavlink/common/mavlink_msg_set_video_stream_settings.h \
    lib/mavlink/common/mavlink_msg_setup_signing.h \
    lib/mavlink/common/mavlink_msg_sim_state.h \
    lib/mavlink/common/mavlink_msg_statustext.h \
    lib/mavlink/common/mavlink_msg_storage_information.h \
    lib/mavlink/common/mavlink_msg_sys_status.h \
    lib/mavlink/common/mavlink_msg_system_time.h \
    lib/mavlink/common/mavlink_msg_terrain_check.h \
    lib/mavlink/common/mavlink_msg_terrain_data.h \
    lib/mavlink/common/mavlink_msg_terrain_report.h \
    lib/mavlink/common/mavlink_msg_terrain_request.h \
    lib/mavlink/common/mavlink_msg_timesync.h \
    lib/mavlink/common/mavlink_msg_v2_extension.h \
    lib/mavlink/common/mavlink_msg_vfr_hud.h \
    lib/mavlink/common/mavlink_msg_vibration.h \
    lib/mavlink/common/mavlink_msg_vicon_position_estimate.h \
    lib/mavlink/common/mavlink_msg_video_stream_information.h \
    lib/mavlink/common/mavlink_msg_vision_position_estimate.h \
    lib/mavlink/common/mavlink_msg_vision_speed_estimate.h \
    lib/mavlink/common/mavlink_msg_wind_cov.h \
    lib/mavlink/common/testsuite.h \
    lib/mavlink/common/version.h \
    lib/mavlink/matrixpilot/matrixpilot.h \
    lib/mavlink/matrixpilot/mavlink.h \
    lib/mavlink/matrixpilot/mavlink_msg_airspeeds.h \
    lib/mavlink/matrixpilot/mavlink_msg_altitudes.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_command.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_directory.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_set.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f17.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f18.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f19.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f20.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f21.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f22.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    lib/mavlink/matrixpilot/testsuite.h \
    lib/mavlink/matrixpilot/version.h \
    lib/mavlink/minimal/mavlink.h \
    lib/mavlink/minimal/mavlink_msg_heartbeat.h \
    lib/mavlink/minimal/minimal.h \
    lib/mavlink/minimal/testsuite.h \
    lib/mavlink/minimal/version.h \
    lib/mavlink/slugs/mavlink.h \
    lib/mavlink/slugs/mavlink_msg_boot.h \
    lib/mavlink/slugs/mavlink_msg_control_surface.h \
    lib/mavlink/slugs/mavlink_msg_cpu_load.h \
    lib/mavlink/slugs/mavlink_msg_ctrl_srfc_pt.h \
    lib/mavlink/slugs/mavlink_msg_data_log.h \
    lib/mavlink/slugs/mavlink_msg_diagnostic.h \
    lib/mavlink/slugs/mavlink_msg_gps_date_time.h \
    lib/mavlink/slugs/mavlink_msg_isr_location.h \
    lib/mavlink/slugs/mavlink_msg_mid_lvl_cmds.h \
    lib/mavlink/slugs/mavlink_msg_novatel_diag.h \
    lib/mavlink/slugs/mavlink_msg_ptz_status.h \
    lib/mavlink/slugs/mavlink_msg_sensor_bias.h \
    lib/mavlink/slugs/mavlink_msg_sensor_diag.h \
    lib/mavlink/slugs/mavlink_msg_slugs_camera_order.h \
    lib/mavlink/slugs/mavlink_msg_slugs_configuration_camera.h \
    lib/mavlink/slugs/mavlink_msg_slugs_mobile_location.h \
    lib/mavlink/slugs/mavlink_msg_slugs_navigation.h \
    lib/mavlink/slugs/mavlink_msg_status_gps.h \
    lib/mavlink/slugs/mavlink_msg_uav_status.h \
    lib/mavlink/slugs/mavlink_msg_volt_sensor.h \
    lib/mavlink/slugs/slugs.h \
    lib/mavlink/slugs/testsuite.h \
    lib/mavlink/slugs/version.h \
    lib/qInstrument/qinstrument.h \
    lib/mavlink/ardupilotmega/ardupilotmega.h \
    lib/mavlink/ardupilotmega/mavlink.h \
    lib/mavlink/ardupilotmega/mavlink_msg_adap_tuning.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ahrs.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ahrs2.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ahrs3.h \
    lib/mavlink/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ap_adc.h \
    lib/mavlink/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    lib/mavlink/ardupilotmega/mavlink_msg_battery2.h \
    lib/mavlink/ardupilotmega/mavlink_msg_camera_feedback.h \
    lib/mavlink/ardupilotmega/mavlink_msg_camera_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_compassmot_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_data16.h \
    lib/mavlink/ardupilotmega/mavlink_msg_data32.h \
    lib/mavlink/ardupilotmega/mavlink_msg_data64.h \
    lib/mavlink/ardupilotmega/mavlink_msg_data96.h \
    lib/mavlink/ardupilotmega/mavlink_msg_device_op_read.h \
    lib/mavlink/ardupilotmega/mavlink_msg_device_op_read_reply.h \
    lib/mavlink/ardupilotmega/mavlink_msg_device_op_write.h \
    lib/mavlink/ardupilotmega/mavlink_msg_device_op_write_reply.h \
    lib/mavlink/ardupilotmega/mavlink_msg_digicam_configure.h \
    lib/mavlink/ardupilotmega/mavlink_msg_digicam_control.h \
    lib/mavlink/ardupilotmega/mavlink_msg_ekf_status_report.h \
    lib/mavlink/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    lib/mavlink/ardupilotmega/mavlink_msg_fence_point.h \
    lib/mavlink/ardupilotmega/mavlink_msg_fence_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gimbal_control.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gimbal_report.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_get_request.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_get_response.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_set_request.h \
    lib/mavlink/ardupilotmega/mavlink_msg_gopro_set_response.h \
    lib/mavlink/ardupilotmega/mavlink_msg_hwstatus.h \
    lib/mavlink/ardupilotmega/mavlink_msg_led_control.h \
    lib/mavlink/ardupilotmega/mavlink_msg_limits_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mag_cal_report.h \
    lib/mavlink/ardupilotmega/mavlink_msg_meminfo.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mount_configure.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mount_control.h \
    lib/mavlink/ardupilotmega/mavlink_msg_mount_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_pid_tuning.h \
    lib/mavlink/ardupilotmega/mavlink_msg_radio.h \
    lib/mavlink/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    lib/mavlink/ardupilotmega/mavlink_msg_rally_point.h \
    lib/mavlink/ardupilotmega/mavlink_msg_rangefinder.h \
    lib/mavlink/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    lib/mavlink/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    lib/mavlink/ardupilotmega/mavlink_msg_rpm.h \
    lib/mavlink/ardupilotmega/mavlink_msg_sensor_offsets.h \
    lib/mavlink/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    lib/mavlink/ardupilotmega/mavlink_msg_simstate.h \
    lib/mavlink/ardupilotmega/mavlink_msg_vision_position_delta.h \
    lib/mavlink/ardupilotmega/mavlink_msg_wind.h \
    lib/mavlink/ardupilotmega/testsuite.h \
    lib/mavlink/ardupilotmega/version.h \
    lib/mavlink/ASLUAV/ASLUAV.h \
    lib/mavlink/ASLUAV/mavlink.h \
    lib/mavlink/ASLUAV/mavlink_msg_asl_obctrl.h \
    lib/mavlink/ASLUAV/mavlink_msg_aslctrl_data.h \
    lib/mavlink/ASLUAV/mavlink_msg_aslctrl_debug.h \
    lib/mavlink/ASLUAV/mavlink_msg_asluav_status.h \
    lib/mavlink/ASLUAV/mavlink_msg_ekf_ext.h \
    lib/mavlink/ASLUAV/mavlink_msg_fw_soaring_data.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_atmos.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_batmon.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_mppt.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_power.h \
    lib/mavlink/ASLUAV/mavlink_msg_sens_power_board.h \
    lib/mavlink/ASLUAV/mavlink_msg_sensorpod_status.h \
    lib/mavlink/ASLUAV/testsuite.h \
    lib/mavlink/ASLUAV/version.h \
    lib/mavlink/autoquad/autoquad.h \
    lib/mavlink/autoquad/mavlink.h \
    lib/mavlink/autoquad/mavlink_msg_aq_esc_telemetry.h \
    lib/mavlink/autoquad/mavlink_msg_aq_telemetry_f.h \
    lib/mavlink/autoquad/testsuite.h \
    lib/mavlink/autoquad/version.h \
    lib/mavlink/common/common.h \
    lib/mavlink/common/mavlink.h \
    lib/mavlink/common/mavlink_msg_actuator_control_target.h \
    lib/mavlink/common/mavlink_msg_adsb_vehicle.h \
    lib/mavlink/common/mavlink_msg_altitude.h \
    lib/mavlink/common/mavlink_msg_att_pos_mocap.h \
    lib/mavlink/common/mavlink_msg_attitude.h \
    lib/mavlink/common/mavlink_msg_attitude_quaternion.h \
    lib/mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
    lib/mavlink/common/mavlink_msg_attitude_target.h \
    lib/mavlink/common/mavlink_msg_auth_key.h \
    lib/mavlink/common/mavlink_msg_autopilot_version.h \
    lib/mavlink/common/mavlink_msg_battery_status.h \
    lib/mavlink/common/mavlink_msg_button_change.h \
    lib/mavlink/common/mavlink_msg_camera_capture_status.h \
    lib/mavlink/common/mavlink_msg_camera_image_captured.h \
    lib/mavlink/common/mavlink_msg_camera_information.h \
    lib/mavlink/common/mavlink_msg_camera_settings.h \
    lib/mavlink/common/mavlink_msg_camera_trigger.h \
    lib/mavlink/common/mavlink_msg_change_operator_control.h \
    lib/mavlink/common/mavlink_msg_change_operator_control_ack.h \
    lib/mavlink/common/mavlink_msg_collision.h \
    lib/mavlink/common/mavlink_msg_command_ack.h \
    lib/mavlink/common/mavlink_msg_command_int.h \
    lib/mavlink/common/mavlink_msg_command_long.h \
    lib/mavlink/common/mavlink_msg_control_system_state.h \
    lib/mavlink/common/mavlink_msg_data_stream.h \
    lib/mavlink/common/mavlink_msg_data_transmission_handshake.h \
    lib/mavlink/common/mavlink_msg_debug.h \
    lib/mavlink/common/mavlink_msg_debug_vect.h \
    lib/mavlink/common/mavlink_msg_distance_sensor.h \
    lib/mavlink/common/mavlink_msg_encapsulated_data.h \
    lib/mavlink/common/mavlink_msg_estimator_status.h \
    lib/mavlink/common/mavlink_msg_extended_sys_state.h \
    lib/mavlink/common/mavlink_msg_file_transfer_protocol.h \
    lib/mavlink/common/mavlink_msg_flight_information.h \
    lib/mavlink/common/mavlink_msg_follow_target.h \
    lib/mavlink/common/mavlink_msg_global_position_int.h \
    lib/mavlink/common/mavlink_msg_global_position_int_cov.h \
    lib/mavlink/common/mavlink_msg_global_vision_position_estimate.h \
    lib/mavlink/common/mavlink_msg_gps2_raw.h \
    lib/mavlink/common/mavlink_msg_gps2_rtk.h \
    lib/mavlink/common/mavlink_msg_gps_global_origin.h \
    lib/mavlink/common/mavlink_msg_gps_inject_data.h \
    lib/mavlink/common/mavlink_msg_gps_input.h \
    lib/mavlink/common/mavlink_msg_gps_raw_int.h \
    lib/mavlink/common/mavlink_msg_gps_rtcm_data.h \
    lib/mavlink/common/mavlink_msg_gps_rtk.h \
    lib/mavlink/common/mavlink_msg_gps_status.h \
    lib/mavlink/common/mavlink_msg_heartbeat.h \
    lib/mavlink/common/mavlink_msg_high_latency.h \
    lib/mavlink/common/mavlink_msg_highres_imu.h \
    lib/mavlink/common/mavlink_msg_hil_actuator_controls.h \
    lib/mavlink/common/mavlink_msg_hil_controls.h \
    lib/mavlink/common/mavlink_msg_hil_gps.h \
    lib/mavlink/common/mavlink_msg_hil_optical_flow.h \
    lib/mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
    lib/mavlink/common/mavlink_msg_hil_sensor.h \
    lib/mavlink/common/mavlink_msg_hil_state.h \
    lib/mavlink/common/mavlink_msg_hil_state_quaternion.h \
    lib/mavlink/common/mavlink_msg_home_position.h \
    lib/mavlink/common/mavlink_msg_landing_target.h \
    lib/mavlink/common/mavlink_msg_local_position_ned.h \
    lib/mavlink/common/mavlink_msg_local_position_ned_cov.h \
    lib/mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    lib/mavlink/common/mavlink_msg_log_data.h \
    lib/mavlink/common/mavlink_msg_log_entry.h \
    lib/mavlink/common/mavlink_msg_log_erase.h \
    lib/mavlink/common/mavlink_msg_log_request_data.h \
    lib/mavlink/common/mavlink_msg_log_request_end.h \
    lib/mavlink/common/mavlink_msg_log_request_list.h \
    lib/mavlink/common/mavlink_msg_logging_ack.h \
    lib/mavlink/common/mavlink_msg_logging_data.h \
    lib/mavlink/common/mavlink_msg_logging_data_acked.h \
    lib/mavlink/common/mavlink_msg_manual_control.h \
    lib/mavlink/common/mavlink_msg_manual_setpoint.h \
    lib/mavlink/common/mavlink_msg_memory_vect.h \
    lib/mavlink/common/mavlink_msg_message_interval.h \
    lib/mavlink/common/mavlink_msg_mission_ack.h \
    lib/mavlink/common/mavlink_msg_mission_clear_all.h \
    lib/mavlink/common/mavlink_msg_mission_count.h \
    lib/mavlink/common/mavlink_msg_mission_current.h \
    lib/mavlink/common/mavlink_msg_mission_item.h \
    lib/mavlink/common/mavlink_msg_mission_item_int.h \
    lib/mavlink/common/mavlink_msg_mission_item_reached.h \
    lib/mavlink/common/mavlink_msg_mission_request.h \
    lib/mavlink/common/mavlink_msg_mission_request_int.h \
    lib/mavlink/common/mavlink_msg_mission_request_list.h \
    lib/mavlink/common/mavlink_msg_mission_request_partial_list.h \
    lib/mavlink/common/mavlink_msg_mission_set_current.h \
    lib/mavlink/common/mavlink_msg_mission_write_partial_list.h \
    lib/mavlink/common/mavlink_msg_mount_orientation.h \
    lib/mavlink/common/mavlink_msg_named_value_float.h \
    lib/mavlink/common/mavlink_msg_named_value_int.h \
    lib/mavlink/common/mavlink_msg_nav_controller_output.h \
    lib/mavlink/common/mavlink_msg_optical_flow.h \
    lib/mavlink/common/mavlink_msg_optical_flow_rad.h \
    lib/mavlink/common/mavlink_msg_param_map_rc.h \
    lib/mavlink/common/mavlink_msg_param_request_list.h \
    lib/mavlink/common/mavlink_msg_param_request_read.h \
    lib/mavlink/common/mavlink_msg_param_set.h \
    lib/mavlink/common/mavlink_msg_param_value.h \
    lib/mavlink/common/mavlink_msg_ping.h \
    lib/mavlink/common/mavlink_msg_play_tune.h \
    lib/mavlink/common/mavlink_msg_position_target_global_int.h \
    lib/mavlink/common/mavlink_msg_position_target_local_ned.h \
    lib/mavlink/common/mavlink_msg_power_status.h \
    lib/mavlink/common/mavlink_msg_protocol_version.h \
    lib/mavlink/common/mavlink_msg_radio_status.h \
    lib/mavlink/common/mavlink_msg_raw_imu.h \
    lib/mavlink/common/mavlink_msg_raw_pressure.h \
    lib/mavlink/common/mavlink_msg_rc_channels.h \
    lib/mavlink/common/mavlink_msg_rc_channels_override.h \
    lib/mavlink/common/mavlink_msg_rc_channels_raw.h \
    lib/mavlink/common/mavlink_msg_rc_channels_scaled.h \
    lib/mavlink/common/mavlink_msg_request_data_stream.h \
    lib/mavlink/common/mavlink_msg_resource_request.h \
    lib/mavlink/common/mavlink_msg_safety_allowed_area.h \
    lib/mavlink/common/mavlink_msg_safety_set_allowed_area.h \
    lib/mavlink/common/mavlink_msg_scaled_imu.h \
    lib/mavlink/common/mavlink_msg_scaled_imu2.h \
    lib/mavlink/common/mavlink_msg_scaled_imu3.h \
    lib/mavlink/common/mavlink_msg_scaled_pressure.h \
    lib/mavlink/common/mavlink_msg_scaled_pressure2.h \
    lib/mavlink/common/mavlink_msg_scaled_pressure3.h \
    lib/mavlink/common/mavlink_msg_serial_control.h \
    lib/mavlink/common/mavlink_msg_servo_output_raw.h \
    lib/mavlink/common/mavlink_msg_set_actuator_control_target.h \
    lib/mavlink/common/mavlink_msg_set_attitude_target.h \
    lib/mavlink/common/mavlink_msg_set_gps_global_origin.h \
    lib/mavlink/common/mavlink_msg_set_home_position.h \
    lib/mavlink/common/mavlink_msg_set_mode.h \
    lib/mavlink/common/mavlink_msg_set_position_target_global_int.h \
    lib/mavlink/common/mavlink_msg_set_position_target_local_ned.h \
    lib/mavlink/common/mavlink_msg_set_video_stream_settings.h \
    lib/mavlink/common/mavlink_msg_setup_signing.h \
    lib/mavlink/common/mavlink_msg_sim_state.h \
    lib/mavlink/common/mavlink_msg_statustext.h \
    lib/mavlink/common/mavlink_msg_storage_information.h \
    lib/mavlink/common/mavlink_msg_sys_status.h \
    lib/mavlink/common/mavlink_msg_system_time.h \
    lib/mavlink/common/mavlink_msg_terrain_check.h \
    lib/mavlink/common/mavlink_msg_terrain_data.h \
    lib/mavlink/common/mavlink_msg_terrain_report.h \
    lib/mavlink/common/mavlink_msg_terrain_request.h \
    lib/mavlink/common/mavlink_msg_timesync.h \
    lib/mavlink/common/mavlink_msg_v2_extension.h \
    lib/mavlink/common/mavlink_msg_vfr_hud.h \
    lib/mavlink/common/mavlink_msg_vibration.h \
    lib/mavlink/common/mavlink_msg_vicon_position_estimate.h \
    lib/mavlink/common/mavlink_msg_video_stream_information.h \
    lib/mavlink/common/mavlink_msg_vision_position_estimate.h \
    lib/mavlink/common/mavlink_msg_vision_speed_estimate.h \
    lib/mavlink/common/mavlink_msg_wind_cov.h \
    lib/mavlink/common/testsuite.h \
    lib/mavlink/common/version.h \
    lib/mavlink/matrixpilot/matrixpilot.h \
    lib/mavlink/matrixpilot/mavlink.h \
    lib/mavlink/matrixpilot/mavlink_msg_airspeeds.h \
    lib/mavlink/matrixpilot/mavlink_msg_altitudes.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_command.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_directory.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    lib/mavlink/matrixpilot/mavlink_msg_flexifunction_set.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f17.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f18.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f19.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f20.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f21.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f22.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    lib/mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    lib/mavlink/matrixpilot/testsuite.h \
    lib/mavlink/matrixpilot/version.h \
    lib/mavlink/minimal/mavlink.h \
    lib/mavlink/minimal/mavlink_msg_heartbeat.h \
    lib/mavlink/minimal/minimal.h \
    lib/mavlink/minimal/testsuite.h \
    lib/mavlink/minimal/version.h \
    lib/mavlink/slugs/mavlink.h \
    lib/mavlink/slugs/mavlink_msg_boot.h \
    lib/mavlink/slugs/mavlink_msg_control_surface.h \
    lib/mavlink/slugs/mavlink_msg_cpu_load.h \
    lib/mavlink/slugs/mavlink_msg_ctrl_srfc_pt.h \
    lib/mavlink/slugs/mavlink_msg_data_log.h \
    lib/mavlink/slugs/mavlink_msg_diagnostic.h \
    lib/mavlink/slugs/mavlink_msg_gps_date_time.h \
    lib/mavlink/slugs/mavlink_msg_isr_location.h \
    lib/mavlink/slugs/mavlink_msg_mid_lvl_cmds.h \
    lib/mavlink/slugs/mavlink_msg_novatel_diag.h \
    lib/mavlink/slugs/mavlink_msg_ptz_status.h \
    lib/mavlink/slugs/mavlink_msg_sensor_bias.h \
    lib/mavlink/slugs/mavlink_msg_sensor_diag.h \
    lib/mavlink/slugs/mavlink_msg_slugs_camera_order.h \
    lib/mavlink/slugs/mavlink_msg_slugs_configuration_camera.h \
    lib/mavlink/slugs/mavlink_msg_slugs_mobile_location.h \
    lib/mavlink/slugs/mavlink_msg_slugs_navigation.h \
    lib/mavlink/slugs/mavlink_msg_status_gps.h \
    lib/mavlink/slugs/mavlink_msg_uav_status.h \
    lib/mavlink/slugs/mavlink_msg_volt_sensor.h \
    lib/mavlink/slugs/slugs.h \
    lib/mavlink/slugs/testsuite.h \
    lib/mavlink/slugs/version.h \
    lib/mavlink/standard/mavlink.h \
    lib/mavlink/standard/standard.h \
    lib/mavlink/standard/testsuite.h \
    lib/mavlink/standard/version.h \
    lib/mavlink/test/mavlink.h \
    lib/mavlink/test/mavlink_msg_test_types.h \
    lib/mavlink/test/test.h \
    lib/mavlink/test/testsuite.h \
    lib/mavlink/test/version.h \
    lib/mavlink/uAvionix/mavlink.h \
    lib/mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.h \
    lib/mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.h \
    lib/mavlink/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.h \
    lib/mavlink/uAvionix/testsuite.h \
    lib/mavlink/uAvionix/uAvionix.h \
    lib/mavlink/uAvionix/version.h \
    lib/mavlink/checksum.h \
    lib/mavlink/mavlink_conversions.h \
    lib/mavlink/mavlink_get_info.h \
    lib/mavlink/mavlink_helpers.h \
    lib/mavlink/mavlink_sha256.h \
    lib/mavlink/mavlink_types.h \
    lib/mavlink/protocol.h \
    lib/ExtPlane-Panel-master/dialogs/bindingcurvedialog.h \
    lib/ExtPlane-Panel-master/dialogs/edititemdialog.h \
    lib/ExtPlane-Panel-master/dialogs/hardwaredialog.h \
    lib/ExtPlane-Panel-master/dialogs/panelitemselectiondialog.h \
    lib/ExtPlane-Panel-master/dialogs/panelsdialog.h \
    lib/ExtPlane-Panel-master/dialogs/settingsdialog.h \
    lib/ExtPlane-Panel-master/hardware/chromaoutputdevice.h \
    lib/ExtPlane-Panel-master/hardware/hardwarebinding.h \
    lib/ExtPlane-Panel-master/hardware/hardwaremanager.h \
    lib/ExtPlane-Panel-master/hardware/nulloutputdevice.h \
    lib/ExtPlane-Panel-master/hardware/outputdevice.h \
    lib/ExtPlane-Panel-master/hardware/pololuoutputdevice.h \
    lib/ExtPlane-Panel-master/hardware/servoblasteroutputdevice.h \
    lib/ExtPlane-Panel-master/needles/gabalancedneedle.h \
    lib/ExtPlane-Panel-master/needles/needle.h \
    lib/ExtPlane-Panel-master/needles/triangleneedle.h \
    lib/ExtPlane-Panel-master/panelitems/airspeedindicator.h \
    lib/ExtPlane-Panel-master/panelitems/altimeter.h \
    lib/ExtPlane-Panel-master/panelitems/attitudeindicator.h \
    lib/ExtPlane-Panel-master/panelitems/button.h \
    lib/ExtPlane-Panel-master/panelitems/compass.h \
    lib/ExtPlane-Panel-master/panelitems/datarefdebugger.h \
    lib/ExtPlane-Panel-master/panelitems/di.h \
    lib/ExtPlane-Panel-master/panelitems/dial.h \
    lib/ExtPlane-Panel-master/panelitems/displayinstrument.h \
    lib/ExtPlane-Panel-master/panelitems/engine_battery.h \
    lib/ExtPlane-Panel-master/panelitems/engine_fuel_p.h \
    lib/ExtPlane-Panel-master/panelitems/engine_rpm.h \
    lib/ExtPlane-Panel-master/panelitems/enginedisplay.h \
    lib/ExtPlane-Panel-master/panelitems/gaugecover.h \
    lib/ExtPlane-Panel-master/panelitems/genericlittlegauge.h \
    lib/ExtPlane-Panel-master/panelitems/gpsmap.h \
    lib/ExtPlane-Panel-master/panelitems/hsi_ks55.h \
    lib/ExtPlane-Panel-master/panelitems/indicatordisplay.h \
    lib/ExtPlane-Panel-master/panelitems/indicatorlight.h \
    lib/ExtPlane-Panel-master/panelitems/mapinstrument.h \
    lib/ExtPlane-Panel-master/panelitems/navdisplay.h \
    lib/ExtPlane-Panel-master/panelitems/needleinstrument.h \
    lib/ExtPlane-Panel-master/panelitems/raspextplaneconnection.h \
    lib/ExtPlane-Panel-master/panelitems/panelitem.h \
    lib/ExtPlane-Panel-master/panelitems/pfddisplay.h \
    lib/ExtPlane-Panel-master/panelitems/radarmap.h \
    lib/ExtPlane-Panel-master/panelitems/rotaryknob.h \
    lib/ExtPlane-Panel-master/panelitems/slipindicator.h \
    lib/ExtPlane-Panel-master/panelitems/switch.h \
    lib/ExtPlane-Panel-master/panelitems/tankleveler.h \
    lib/ExtPlane-Panel-master/panelitems/turnbank.h \
    lib/ExtPlane-Panel-master/panelitems/variometer.h \
    lib/ExtPlane-Panel-master/util/console.h \
    lib/ExtPlane-Panel-master/util/interpolation.h \
    lib/ExtPlane-Panel-master/util/perlinnoise.h \
    lib/ExtPlane-Panel-master/widgets/colorselector.h \
    lib/ExtPlane-Panel-master/widgets/distanceunitcombobox.h \
    lib/ExtPlane-Panel-master/widgets/numberinputlineedit.h \
    lib/ExtPlane-Panel-master/widgets/velocityunitcombobox.h \
    lib/ExtPlane-Panel-master/menubutton.h \
    lib/ExtPlane-Panel-master/panel.h \
    lib/ExtPlane-Panel-master/panelitemfactory.h \
    lib/ExtPlane-Panel-master/panelwindow.h \
    lib/ExtPlane-Panel-master/settings.h \
    lib/ExtPlane-Panel-master/units.h \
    lib/ExtPlane-Panel-master/valueinterpolator.h \
    lib/ExtPlane-Panel-master/panelitems/clientdataref.h \
    lib/ExtPlane-Panel-master/panelitems/clientdatarefprovider.h \
    lib/ExtPlane-Panel-master/panelitems/extplaneclient.h \
    lib/ExtPlane-Panel-master/panelitems/extplaneconnection.h \
    lib/ExtPlane-Panel-master/panelitems/simulatedextplaneconnection.h \
    lib/ExtPlane-Panel-master/panelitems/simulateddatarefs/alternatingsimulateddataref.h \
    lib/ExtPlane-Panel-master/panelitems/simulateddatarefs/fixedsimulateddataref.h \
    lib/ExtPlane-Panel-master/panelitems/simulateddatarefs/simulateddataref.h \
    lib/sql.h \
    lib/QMapControl/qmapcontrol_global.h                        \
    lib/QMapControl/Geometry.h                                  \
    lib/QMapControl/GeometryLineString.h                        \
    lib/QMapControl/GeometryPoint.h                             \
    lib/QMapControl/GeometryPointShape.h                        \
    lib/QMapControl/GeometryPointShapeScaled.h                  \
    lib/QMapControl/GeometryPointArrow.h                        \
    lib/QMapControl/GeometryPointCircle.h                       \
    lib/QMapControl/GeometryPointImage.h                        \
    lib/QMapControl/GeometryPointImageScaled.h                  \
    lib/QMapControl/GeometryPolygon.h                           \
    lib/QMapControl/GeometryPolygonImage.h                      \
    lib/QMapControl/GeometryWidget.h                            \
    lib/QMapControl/GPS_Position.h                              \
    lib/QMapControl/ImageManager.h                              \
    lib/QMapControl/Layer.h                                     \
    lib/QMapControl/LayerGeometry.h                             \
    lib/QMapControl/LayerMapAdapter.h                           \
    lib/QMapControl/MapAdapter.h                                \
    lib/QMapControl/MapAdapterGoogle.h                          \
    lib/QMapControl/MapAdapterOSM.h                             \
    lib/QMapControl/MapAdapterTile.h                            \
    lib/QMapControl/MapAdapterWMS.h                             \
    lib/QMapControl/MapAdapterYahoo.h                           \
    lib/QMapControl/NetworkManager.h                            \
    lib/QMapControl/Point.h                                     \
    lib/QMapControl/Projection.h                                \
    lib/QMapControl/ProjectionEquirectangular.h                 \
    lib/QMapControl/ProjectionSphericalMercator.h               \
    lib/QMapControl/QMapControl.h                               \
    lib/QMapControl/QuadTreeContainer.h                         \
    lib/QMapControl/QProgressIndicator.h


INCLUDEPATH = \
    lib/ExtPlane-Panel-master/. \
    lib/ExtPlane-Panel-master/dialogs \
    lib/ExtPlane-Panel-master/hardware \
    lib/ExtPlane-Panel-master/needles \
    lib/ExtPlane-Panel-master/panelitems \
    lib/ExtPlane-Panel-master/util \
    lib/ExtPlane-Panel-master/widgets \
    lib/QMapControl

FORMS += \
        mainwindow.ui \
    lib/ExtPlane-Panel-master/dialogs/bindingcurvedialog.ui \
    lib/ExtPlane-Panel-master/dialogs/settingsdialog.ui \
    lib/ExtPlane-Panel-master/dialogs/panelsdialog.ui \
    lib/ExtPlane-Panel-master/dialogs/panelitemselectiondialog.ui \
    lib/ExtPlane-Panel-master/dialogs/hardwaredialog.ui \
    lib/ExtPlane-Panel-master/dialogs/edititemdialog.ui

DISTFILES += \
    config/config.ini \
    lib/ExtPlane-Panel-master/images/bezel2.png \
    lib/ExtPlane-Panel-master/images/bezel_square_.png \
    lib/ExtPlane-Panel-master/images/DR400_Battery_Amp.png \
    lib/ExtPlane-Panel-master/images/DR400_engine_FUELP.png \
    lib/ExtPlane-Panel-master/images/DR400_engine_FUEL_Tank.png \
    lib/ExtPlane-Panel-master/images/DR400_engine_FUEL_Tank_needle.png \
    lib/ExtPlane-Panel-master/images/DR400_engine_generic.png \
    lib/ExtPlane-Panel-master/images/DR400_engine_generic_needle.png \
    README.md

SUBDIRS += \

RESOURCES += \
    lib/ExtPlane-Panel-master/applicationresources.qrc \

